### PR TITLE
Update MySQL to 5.7.31

### PR DESCRIPTION
**Pull request by dggreenbaum**
Updates MySQL to the latest 5.7 build at time of writing.

### CODE REVIEW

**Comment by jkemp101** [comment]
I did a review of the major changes for each release and nothing jumped out. I think we went from 5.6 to 5.7 without issues so hopefully this would be uneventful also.

**Review by jkemp101 — APPROVED** [review]

**Review by thomasst — APPROVED** [review]
We'd want to change it here as well:

https://github.com/closeio/devtools/blob/master/docker-compose.yaml#L396

I haven't encountered any issues (and wouldn't expect any).

I did get this warning repeatedly after running the updated MySQL version:

```
nylas_mysql_1                 | 2020-10-08T21:29:29.178595Z 0 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
```

**Comment by dggreenbaum** [comment]
@thomasst it looks like RDS will run the `mysql_upgrade` command during the upgrade.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.MySQL.html

I'll test this against a snapshot of a prod instance to make sure we don't get these warnings.

**Comment by dggreenbaum** [comment]
devtools PR: https://github.com/closeio/devtools/pull/158

**Pull request merged**
